pipeline {
    agent any
   //    label 'android-poc-slave'
    stages {
        stage('Build') {
            steps {
                sh 'cd samples/helloworld'
                sh 'dotnet run'
            }
        }
    }}
